version: '3.9'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: newgrad.works
    volumes:
      - ./api:/backend/api
      - ./clerk.prod.pem:/backend/clerk.prod.pem
      - ./.env:/backend/.env
    ports:
      - "8002:8000"
    environment:
      - IS_PROD=1
